[package]
name = "tokio-scheduler-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
exclude = [
    './tests'
]

[dependencies]
serde_json = "^1"
serde = "^1"
uuid = { version = "^1",features = ["v4","fast-rng"] }
cron = "^0"
chrono = "^0"
tokio = {version = "^1",features = ["full"]}
once_cell = "^1"
async-trait = "^0"

[dev-dependencies]
chrono-tz = "^0"