on:
  push:
    tags:
      - '*'

jobs:
  check:
    name: Check and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check crate
        run: cargo check
      - name: Test crate
        run: cargo test

  publish:
    name: Publish
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push types to crates.io
        working-directory: tokio-scheduler-types
        run: |
          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo publish -v
      - name: Push macro to crates.io
        working-directory: tokio-scheduler-macro
        run: |
          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo publish -v
      - name: Publish to crates.io
        run: |
          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo publish -v
    
