on:
  push:
    tags:
      - '*'
  
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check crate
        run: cargo check

  publish:
    name: Publish
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Publish to crates.io
      run: |
        cargo login ${{ secrets.CRATES_TOKEN }}
        cargo publish -v
    
